const API_END_POINTS = {
  baseURL: "http://localhost:8080/api",
  // baseURL: "https://subwayapi1.corepeelers.com/api",
  login: "/auth/login",
  GET_MODULE_LIST: "/module/getAllModules",
  CREATE_MODULE: "/module/createModule",
  DELETE_MODULE: "/module/deleteModule",
  GET_GROUP_LIST: "/group/getAllGroups",
  CREATE_GROUP: "/group/createGroup",
  DELETE_GROUP: "/group/deleteGroup",
  GET_PERMISSION_LIST: "/permission/getAllPermissions",
  CREATE_PERMISSION: "/permission/createPermission",
  DELETE_PERMISSION: "/permission/deletePermission",
  GET_GROUP_MODULES: "/group/getGroupModules",
  UPDATE_GROUP_MODULE_MAPPING: "/group/updateGroupModuleMapping",
  GET_USER_LIST: "/user/getAllUsers",
  CREATE_USER: "/user/createUser",
  UPDATE_USER: "/user/updateUser",
  UPDATE_PASSWORD: "/user/updatePassword",
  GET_USER_MODULES: "/user/getUserModules",
  UPDATE_USER_MODULE_MAPPING: "/user/updateUserModuleMapping",
  GET_TOOLS: "/tool/getAllTools",
  CREATE_TOOL: "/tool/createTool",
  UPDATE_TOOL: "/tool/updateTool",
  DELETE_TOOL: "/tool/deleteTool",
  GET_ORGANIZATION: "/organization/all",
  ADD_ORGANIZATION: "/organization/create",
  UPDATE_ORGANIZATION: "/organization/update",
  UPDATE_ORGANIZATION_TOOLS: "/organization/tools/assign",
  GET_ORGANIZATION_TOOLS: "/organization/tools/",
  GET_ORGANIZATION_DASHBOARD: "/organization/dashboard",
  GET_ORGANIZATION_MODULES: "/organization/getOrganizationModules",
  UPDATE_ORGANIZATION_MODULE_MAPPING: "/organization/updateOrganizationModules",
  ACTIVITY_USER_LIST: `/audit_log/user/list`,
  ACTIVITY_SEARCH: `/audit_log/list`,
};

export default API_END_POINTS;
